---
- name: Ensure required packages are installed
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - curl
    - tar

- name: Get the latest k9s version
  shell: curl -s https://api.github.com/repos/derailed/k9s/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/'
  register: k9s_version
  changed_when: false

- name: Download k9s binary
  get_url:
    url: "https://github.com/derailed/k9s/releases/download/{{ k9s_version.stdout }}/k9s_Linux_amd64.tar.gz"
    dest: /tmp/k9s.tar.gz

- name: Extract k9s binary
  unarchive:
    src: /tmp/k9s.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move k9s binary to /usr/local/bin
  copy:
    src: /tmp/k9s
    dest: /usr/local/bin/k9s
    mode: '0755'

- name: Verify k9s installation
  command: k9s version
  register: k9s_version_output
  changed_when: false

- name: Print k9s version
  debug:
    msg: "k9s version installed: {{ k9s_version_output.stdout }}"

