---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-rolling-restart-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-rolling-restart-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-rolling-restart-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-rolling-restart-role
subjects:
  - kind: ServiceAccount
    name: vault-rolling-restart-sa
    namespace: vault
