version: '3'

tasks:
  upgrade_1_replica:
    desc: Helm upgrade with 1 Vault replica
    cmds:
      - helm upgrade vault . --install -n vault --set vault.server.ha.enabled=true,vault.server.ha.replicas=1,vault.server.ha.raft.enabled=true,vault.server.ha.raft.setNodeId=true,vault.injector.enabled=false,job.enabled=false {{.ARGS}}
    silent: true
    vars:
      ARGS: ""
  upgrade_no_restart:
    desc: Helm upgrade with no restart
    cmds:
      - helm upgrade vault . --install -n vault --set vault.server.ha.enabled=true,vault.server.ha.replicas=5,vault.server.ha.raft.enabled=true,vault.server.ha.raft.setNodeId=true,vault.injector.enabled=false,job.enabled=false {{.ARGS}}
    silent: true
    vars:
      ARGS: ""
  upgrade_with_restart:
    desc: Helm upgrade with restart
    cmds:
      - helm upgrade vault . --install -n vault -f sandbox.yaml {{.ARGS}}
    silent: true
    vars:
      ARGS: ""