---
- name: Create argocd namespace if it doesn't exist
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: argocd

- name: Download ArgoCD installation manifest
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
    dest: /tmp/argocd-install.yaml

- name: Apply ArgoCD manifest
  kubernetes.core.k8s:
    state: present
    src: /tmp/argocd-install.yaml
    namespace: argocd

- name: Install Vault ArgoCD Application
  kubernetes.core.k8s:
    state: present
    src: argocd/vault-sandbox.yaml
    namespace: argocd

- name: Install Traefik ArgoCD Application
  kubernetes.core.k8s:
    state: present
    src: argocd/traefik-sandbox.yaml
    namespace: argocd

- name: Install MetalLB ArgoCD Application
  kubernetes.core.k8s:
    state: present
    src: argocd/metallb-sandbox.yaml
    namespace: argocd

# - name: Generate a random base64-encoded key
#   ansible.builtin.command: "openssl rand -base64 128"
#   register: random_key

# - name: Create or update the MetalLB memberlist secret
#   community.kubernetes.k8s:
#     state: present
#     kubeconfig: ~/.kube/config
#     definition:
#       apiVersion: v1
#       kind: Secret
#       metadata:
#         name: metallb-memberlist
#         namespace: metallb-system
#       type: Opaque
#       data:
#         secretkey: "{{ random_key.stdout | b64encode }}"
#   when: random_key.changed
