name: Release

on:
  push:
    branches:
      - main
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  release:
    name: Release using release-please
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.0

      - name: Run release-please
        id: release
        uses: googleapis/release-please-action@v4.1.3
        with:
          release-type: simple
          package-name: popos-playbook
          token: ${{ secrets.Z_GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1

      - name: Log in to DockerHub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.Z_DOCKER_USERNAME }}
          password: ${{ secrets.Z_DOCKER_PASSWORD }}

      - name: Build and push Docker image
        id: docker_build
        uses: docker/build-push-action@v6.9.0
        with:
          context: vault/image
          push: true
          tags: |
            wsams/bitnami-kubectl:latest
            wsams/bitnami-kubectl:${{ steps.release.outputs.release-version }}

